######################## default configuration ####################
baseURL = "https://whereimreallyfrom.com/"
title = "Where I'm Really From"
theme = "twentytwenty"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45

############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Read"
URL = "read"
weight = 2

[[menu.main]]
name = "Submit"
URL = "submit"
weight = 3

[[menu.main]]
name = "Resources"
URL = "resources"
weight = 4

[[menu.main]]
name = "Podcast"
URL = "podcast"
weight = 5

[[menu.main]]
name = "About Us"
URL = "about"
weight = 6

# only desktop menu
[[menu.desktop]]
name = "Submit"
URL = "submit"
weight = 1

[[menu.desktop]]
name = "Check out our podcast!"
URL = "podcast"
weight = 2


#################### default parameters ################################
[params]
# Meta data
description = "Online Archive of Asian American Narratives"
author = "Robin Zeng"
favicon = "/images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
image = "/images/logo.png"
heading = "Stories from the Asian American Diaspora"

# original call to action
[params.call_to_action]
enable = true
title = "We'd love to hear your perspective"
content = "We're collecting stories from Asian America - when, why, and how we came to be where we are today. We hope that our stories can help Asian Americans everywhere better understand what ties us together."
button_label = "Share your story now"
button_url = "submit"

# read
[params.read]
heading = "Check out some of our recent submissions" 

############################# social site ########################
[params.social]
email = "wirfeditors@gmail.com"
instagram = "https://www.instagram.com/aab_pod/"
spotify = "https://open.spotify.com/show/2VnJjutE1eQ2aTnccDaAPy"
apple = "https://podcasts.apple.com/us/podcast/asian-american-brainstorm/id1564628161"
youtube = "https://www.youtube.com/playlist?list=PLhk-Ayhk2bpdfgVhJZPqYica94vK9ilbk"
