baseURL = "http://www.whereimreallyfrom.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Where I'm Really From"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "read"
name = "Read"
weight = 1
[[Languages.en.menu.footer]]
URL = "contact"
name = "Submit"
weight = 2
[[Languages.en.menu.footer]]
URL = "resources"
name = "Resources"
weight = 3
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "read"
name = "Read"
weight = 2
[[Languages.en.menu.main]]
hasChildren = true
URL = "contact"
name = "Submit"
weight = 3
[[Languages.en.menu.main]]
URL = "tips"
name = "Tips"
parent = "Submit"
[[Languages.en.menu.main]]
URL = "guidelines"
name = "Guidelines"
parent = "Submit"
[[Languages.en.menu.main]]
URL = "contact"
name = "Submit a Story"
parent = "Submit"
[[Languages.en.menu.main]]
hasChildren = true
URL = "learn"
name = "Learn"
weight = 4
[[Languages.en.menu.main]]
URL = "about"
name = "About Us"
parent = "Learn"
[[Languages.en.menu.main]]
URL = "resources"
name = "Resources"
parent = "Learn"

[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Robin Zeng"
contact_form_action = "#"
description = "An Archive of Asian-American Stories"
email = "wirfeditors@email.com"
google_analitycs_id = ""
location = "USA"
logo = "images/logo.png"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
[[params.social]]
icon = "ion-social-instagram-outline"
link = "#"
